//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeartRateAnalyzer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://neurul.ngrok.io/heartrate/")]
        public string AvatarUrl {
            get {
                return ((string)(this["AvatarUrl"]));
            }
            set {
                this["AvatarUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4c62001e-8f0c-4775-8475-d461a5f42bca")]
        public string HeartRateId {
            get {
                return ((string)(this["HeartRateId"]));
            }
            set {
                this["HeartRateId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8c4df9d3-9fc8-4377-b43d-4db544abc9f2")]
        public string AnalyzedId {
            get {
                return ((string)(this["AnalyzedId"]));
            }
            set {
                this["AnalyzedId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16de4a5a-361c-4de5-8a2a-ec5f5addb21d")]
        public string WarningId {
            get {
                return ((string)(this["WarningId"]));
            }
            set {
                this["WarningId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("578c3f3d-388e-48e3-b71a-3399df62c94e")]
        public string RelaxedId {
            get {
                return ((string)(this["RelaxedId"]));
            }
            set {
                this["RelaxedId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2937b2cc-281f-4307-af67-1bf81708345d")]
        public string AnalyzerAuthorId {
            get {
                return ((string)(this["AnalyzerAuthorId"]));
            }
            set {
                this["AnalyzerAuthorId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("f8f59181-091b-4454-852a-61d6873a563f")]
        public string GetId {
            get {
                return ((string)(this["GetId"]));
            }
            set {
                this["GetId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c42b7fed-acbb-4d0d-bebe-3a2e6fbc1fd9")]
        public string EventsId {
            get {
                return ((string)(this["EventsId"]));
            }
            set {
                this["EventsId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c859ff31-4b25-4dda-8c3b-93f67c5004d7")]
        public string UnknownRateId {
            get {
                return ((string)(this["UnknownRateId"]));
            }
            set {
                this["UnknownRateId"] = value;
            }
        }
    }
}
